invent_pc/api/urls.py
from django.conf import settings
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from api.views import CompCreateViewSet, HostCreateViewSet


# Версия API
API_VERSION = settings.API_VERSION

router = DefaultRouter()
router.register('comps', CompCreateViewSet)
router.register('vms', HostCreateViewSet)

urlpatterns = [
    path(f'{API_VERSION}/', include(router.urls)),
]

invent_pc/invent_pc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('comps.urls', namespace='comps')),
]

invent_pc/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'


urlpatterns = [
    path('edit-user/', views.edit_user, name='edit_user'),
    path('get-rdlogins/', views.get_rdlogins, name='get_rdlogins'),
    path('get-vpns/', views.get_vpns, name='get_vpns'),
    path('update-users-data/',
         views.update_users_data,
         name='update_users_data'),
    path('generate-users-report/',
         views.generate_users_report,
         name='generate_users_report'),
    path('generate-radius-report/',
         views.generate_radius_report,
         name='generate_radius_report'),
    path('generate-vpn-report/',
         views.generate_vpn_report,
         name='generate_vpn_report'),
    path('login/', auth_views.LoginView.as_view(
        template_name='users/registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='users/registration/logged_out.html'), name='logout'),
    path('ad/', views.users_main, name='users_main'),
    path('radius/', views.users_radius, name='users_radius'),
    path('vpn/', views.users_vpn, name='users_vpn'),
    path('gigro/', views.users_gigro, name='users_gigro'),
]

invent_pc/templates/base.html
<!-- templates/base.html -->

<!DOCTYPE html> 
<html lang="ru">
  <head>
    <meta charset="utf-8"> <!-- Кодировка сайта -->
    {% load static %}
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href=" {% static 'css/select2.min.css' %}"/>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/edit_user.js' %}"></script>
    <script src="{% static 'js/select2.min.js' %}"></script>
    <script src="{% static 'js/edit_expiration_date.js' %}"></script>
    <script>
      var edit_user_url = "{% url 'users:edit_user' %}";
      var csrf_token = "{{ csrf_token }}";
    </script>
    <title>
      {% block title %}
        Invent PC
      {% endblock %}
    </title>
  </head>
  <body>
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      <div class="container-fluid py-3 custom-container">
        {% block content %}
          Контент не подвезли
        {% endblock %}
      </div>
    </main>
    <footer class="border-top text-center py-3">
        {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>