invent_pc/api/urls.py
from django.conf import settings
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from api.views import CompCreateViewSet, HostCreateViewSet


# Версия API
API_VERSION = settings.API_VERSION

router = DefaultRouter()
router.register('comps', CompCreateViewSet)
router.register('vms', HostCreateViewSet)

urlpatterns = [
    path(f'{API_VERSION}/', include(router.urls)),
]

invent_pc/comps/urls.py
from django.urls import path

from . import views

app_name = 'comps'


urlpatterns = [
    path('', views.index, name='index'),
    path('reports/',
         views.reports, name='reports'),
    path('comps_by_item/<slug:item_type>/',
         views.comps_by_item, name='comps_by_item'),
    path('departments/',
         views.departments, name='departments'),
    path('vms/', views.vms, name='vms'),
    path('departments/<int:department_id>/delete',
         views.department_delete, name='department_delete'),
    path('<str:pc_name>/', views.comp_detail, name='comp_detail'),
    path('<str:pc_name>/<str:item>/<slug:item_status>/<int:item_id>',
         views.item_edit, name='item_edit'),
    path('<str:pc_name>/delete/',
         views.comp_delete, name='comp_delete'),
]

invent_pc/invent_pc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('comps.urls', namespace='comps')),
]

invent_pc/comps/models.py
from datetime import datetime, timedelta

from django.db import models
from django.utils import timezone
from django.conf import settings


class ItemsChoices(models.TextChoices):
    LOST = 'lost', 'Потерян'
    INSTALLED = 'installed', 'Установлен'
    UNINSTALLED = 'uninstalled', 'Снят'


class Disk(models.Model):
    model = models.CharField('Модель', max_length=100)
    install_date = models.DateTimeField(
        'Дата установки',
        auto_now_add=True
    )
    uninstall_date = models.DateTimeField(
        'Дата снятия',
        null=True,
        blank=True,
        default=None
    )
    capacity = models.CharField('Объем, Гб.', max_length=20)
    serial_number = models.CharField(
        'Серийный номер',
        max_length=100,
        null=True,
        blank=True,
        default='Отсутствует'
    )
    comp = models.ForeignKey(
        'Comp',
        related_name='disks',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name='Компьютер'
    )
    status = models.CharField(
        max_length=15,
        choices=ItemsChoices.choices,
        default=ItemsChoices.INSTALLED,
        verbose_name='Статус диска',
    )

    def __str__(self):
        return f'{self.capacity} GB'

    class Meta:
        ordering = ('uninstall_date',)
        verbose_name = 'Диск'
        verbose_name_plural = 'Диски'


class Ram(models.Model):
    model = models.CharField('Модель', max_length=100)
    install_date = models.DateTimeField(
        'Дата установки',
        auto_now_add=True
    )
    uninstall_date = models.DateTimeField(
        'Дата снятия',
        null=True,
        blank=True,
        default=None
    )
    capacity = models.CharField('Объем, Гб.', max_length=20)
    serial_number = models.CharField(
        'Серийный номер',
        max_length=100,
        null=True,
        blank=True,
        default='Отсутствует'
    )
    comp = models.ForeignKey(
        'Comp',
        related_name='rams',
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    status = models.CharField(
        max_length=15,
        choices=ItemsChoices.choices,
        default=ItemsChoices.INSTALLED,
        verbose_name='Статус модуля памяти',
    )

    def __str__(self):
        return f'{self.capacity} GB'

    class Meta:
        ordering = ('uninstall_date',)
        verbose_name = 'RAM'
        verbose_name_plural = 'RAMs'


class Monitor(models.Model):
    model = models.CharField('Модель', max_length=100)
    install_date = models.DateTimeField(
        'Дата установки',
        auto_now_add=True
    )
    uninstall_date = models.DateTimeField(
        'Дата снятия',
        null=True,
        blank=True,
        default=None
    )
    manufacturer = models.CharField('Производитель', max_length=50)
    serial_number = models.CharField(
        'Серийный номер',
        max_length=100,
        null=True,
        blank=True,
        default='Отсутствует'
    )
    comp = models.ForeignKey(
        'Comp',
        related_name='monitors',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name='Компьютер'
    )
    status = models.CharField(
        max_length=15,
        choices=ItemsChoices.choices,
        default=ItemsChoices.INSTALLED,
        verbose_name='Статус',
    )

    def __str__(self):
        return f'{self.manufacturer} {self.model}'

    class Meta:
        ordering = ('uninstall_date',)
        verbose_name = 'Монитор'
        verbose_name_plural = 'Мониторы'


class WebCamera(models.Model):
    model = models.CharField('Модель', max_length=100, unique=True)

    def __str__(self):
        return self.model

    class Meta:
        ordering = ('model',)
        verbose_name = 'Веб-камера'
        verbose_name_plural = 'Веб-камеры'


class Department(models.Model):
    "Отделы в которых расположены компьютеры."
    name = models.CharField('Департамент', max_length=200, unique=True)

    def __str__(self) -> str:
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = 'Департамент'
        verbose_name_plural = 'Департаменты'


class Comp(models.Model):
    pc_name = models.CharField('Имя ПК', max_length=100)
    add_date = models.DateTimeField(
        'Дата добавления',
        auto_now_add=True
    )
    online_date = models.DateTimeField(
        'Дата последнего подключения',
        default=datetime(2000, 1, 1)
    )
    win_ver = models.CharField('Версия ОС', max_length=100)
    os_arch = models.CharField('Архитектура', max_length=20)
    cpu = models.CharField('Процессор', max_length=50)
    motherboard = models.CharField('Материнская плата', max_length=100)
    department = models.ForeignKey(
        Department,
        related_name='comp',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name='Департамент'
    )
    web_camera = models.ForeignKey(
        WebCamera,
        related_name='comp',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name='Веб-камера'
    )

    def is_offline_long_time(self):
        """Определение компьютеров с большим офлайн периодом, для удаления."""
        days = timezone.now() - timedelta(days=settings.DAYS_OFFLINE)
        return self.online_date < days

    def __str__(self):
        return self.pc_name

    class Meta:
        ordering = ('-add_date',)
        verbose_name = 'Компьютер'
        verbose_name_plural = 'Компьютеры'


class Host(models.Model):
    """Хосты с гипервизорами."""
    name = models.CharField('Имя хоста', max_length=100)
    vms = models.ManyToManyField('VirtualMachine',
                                 verbose_name='Виртуальные машины',
                                 through='HostVirtualMachine')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = 'Хост'
        verbose_name_plural = 'Хосты'


class VirtualMachine(models.Model):
    """Виртуальные машины."""
    name = models.CharField('Имя виртуальной машины', max_length=100)
    uptime = models.DurationField(default=timedelta(seconds=1))
    vm_id = models.CharField(
        'ID виртуальной машины',
        max_length=100,
        default='Не определен'
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        verbose_name = 'Виртуальная машина'
        verbose_name_plural = 'Виртуальные машины'


class HostVirtualMachine(models.Model):
    "Связь виртуальных машин с хостами."
    host = models.ForeignKey(
        'Host',
        on_delete=models.CASCADE,
        related_name='host_vm',
        verbose_name='Хост'
    )
    vm = models.ForeignKey(
        'VirtualMachine',
        on_delete=models.CASCADE,
        related_name='host_vm',
        verbose_name='Виртуальная машина'
    )


class VMAdapter(models.Model):
    """Сетевые адаптеры виртуальных машин."""
    mac = models.CharField('Мак-адрес', max_length=50)
    vlan = models.IntegerField('VlanID')
    vm = models.ForeignKey(
        VirtualMachine,
        related_name='adapter',
        on_delete=models.CASCADE,
        verbose_name='Виртуальная машина'
    )

    def is_duplicate(self):
        """Метод для определения дубликатов мак-адресов."""
        count_mac = VMAdapter.objects.filter(mac=self.mac).count()
        return count_mac > settings.COUNT_MAC

invent_pc/comps/forms.py
from django import forms

from comps.models import Department


class DepartmentFilterForm(forms.Form):
    department = forms.ModelChoiceField(
        queryset=Department.objects.all().order_by('name'),
        label='',
        required=False,
        empty_label=None)

    class Meta:
        model = Department
        fields = ('department',)

invent_pc/comps/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.db.models import Count, Q

from .models import (Comp, Disk, ItemsChoices,
                     Monitor, Ram, Department,
                     Host, VirtualMachine)
from .filters import CompFilter, DiskFilter, RamFilter, MonitorFilter
from .forms import DepartmentFilterForm
from utils.utils import get_pages, get_counters, sorted_list


@login_required
def index(request):
    """Список всех компьютеров."""
    filter_form = DepartmentFilterForm(request.GET)
    comps_filter = CompFilter(request.GET, queryset=Comp.objects.all())

    page_obj = get_pages(request, comps_filter.qs)
    current_query_params = request.GET.copy()
    current_query_params.pop('page', None)

    context = {
        'page_obj': page_obj,
        'filter_form': filter_form,
        'current_query_params': current_query_params,
        'comps_count': comps_filter.qs.count(),
    }

    return render(request, 'comps/index.html', context)


@login_required
def comp_detail(request, pc_name):
    """Детальная информация о компьютере."""
    comp = get_object_or_404(Comp, pc_name=pc_name)
    context = {
        'comp': comp,
    }
    return render(request, 'comps/comp_detail.html', context)


@login_required
def comp_delete(request, pc_name):
    """Удалить компьютер."""
    comp = get_object_or_404(Comp, pc_name=pc_name)
    comp.delete()
    return redirect('comps:index')


@login_required
def item_edit(request, pc_name, item, item_status, item_id):
    """Подтверждение установки/снятие диска на компьютере."""
    models = {
        'disk': Disk,
        'ram': Ram,
        'monitor': Monitor,
    }
    model = models[item]
    item = get_object_or_404(model, pk=item_id)

    if item_status == ItemsChoices.INSTALLED:
        item.install_date = timezone.now()
        item.uninstall_date = None
        item.status = ItemsChoices.INSTALLED

    if item_status == ItemsChoices.UNINSTALLED:
        item.uninstall_date = timezone.now()
        item.status = ItemsChoices.UNINSTALLED

    item.save()

    return redirect('comps:comp_detail', pc_name=pc_name)


@login_required
def reports(request):
    """Общая статистика."""
    filter_form = DepartmentFilterForm(request.GET)
    comps_filter = CompFilter(request.GET, queryset=Comp.objects.all())
    disk_filter = DiskFilter(request.GET, queryset=Disk.objects.filter())
    ram_filter = RamFilter(request.GET, queryset=Ram.objects.filter())
    monitor_filter = MonitorFilter(
        request.GET, queryset=Monitor.objects.filter())

    items = [('motherboard', comps_filter.qs),
             ('win_ver', comps_filter.qs),
             ('os_arch', comps_filter.qs),
             ('cpu', comps_filter.qs),
             ('disks', disk_filter.qs),
             ('rams', ram_filter.qs),
             ('monitors', monitor_filter.qs)]

    context = {
        'comps_count': comps_filter.qs.count(),
        'filter_form': filter_form,
    }

    for item, queryset in items:
        if item in ['disks', 'rams', 'monitors']:
            count_by_item = get_counters(queryset.values('model'), 'model')
        else:
            count_by_item = get_counters(queryset.values(item), item)
        context[f'count_by_{item}'] = sorted_list(count_by_item)

    return render(request, 'comps/reports.html', context)


@login_required
def comps_by_item(request, item_type):
    """Список компьютеров с выбранным оборудованием."""
    item = request.GET.get('item')
    department_id = request.GET.get('department')
    filter_form = DepartmentFilterForm(request.GET)
    item_types = {
        'os_arch': Q(os_arch=item),
        'motherboard': Q(motherboard=item),
        'win_ver': Q(win_ver=item),
        'cpu': Q(cpu=item),
        'disk': Q(disks__model=item, disks__status=ItemsChoices.INSTALLED),
    }
    comps = Comp.objects.filter(item_types.get(item_type, Q()))
    if item_type == 'disk':
        comps = comps.distinct()
    if department_id:
        comps = comps.filter(department=department_id)

    page_obj = get_pages(request, comps)
    current_query_params = request.GET.copy()
    current_query_params.pop('page', None)

    context = {'page_obj': page_obj,
               'filter_form': filter_form,
               'item': item,
               'current_query_params': current_query_params}

    return render(request, 'comps/comps_by_items.html', context)


@login_required
def departments(request):
    """Список отделов с количеством компов."""
    departments = Department.objects.all().order_by('name')
    context = {'departments': departments}
    return render(request, 'comps/departments.html', context)


@login_required
def department_delete(request, department_id):
    """Удалить департамент."""
    department = get_object_or_404(Department, id=department_id)
    department.delete()
    return redirect('comps:departments')


@login_required
def vms(request):
    """Список хостов с виртуальными машинами."""
    hosts = Host.objects.all().prefetch_related(
        'vms').annotate(vms_count=Count('vms')).order_by('-vms_count')
    # Удаление виртуальных машине не имеющих связи с хостами
    VirtualMachine.objects.filter(host_vm__isnull=True).delete()
    vms_count = sum([host.vms_count for host in hosts])
    context = {'hosts': hosts,
               'vms_count': vms_count}
    return render(request, 'comps/vms.html', context)

invent_pc/templates/comps/comp_detail.html
<!-- templates/posts/post_detail.html -->

{% extends 'base.html' %}
{% block title %}
  Компьютер {{ comp.pc_name}}
{% endblock %}
{% block content %}
  <!-- <div class="container-lg py-5 custom-container"> -->
  <div class="py-5 custom-container">
    <!-- <a class="btn btn-primary"
      href="{% url 'comps:index' %}"
    >
      На главную
    </a> -->
    <h1>
      Детали компьютера
    </h1>
    <div class="row">
      <div class="col-md-4">
        <ul class="list-group">
          <li class="custom-list-item">
            Имя компютера: <b><span>{{ comp.pc_name }}</span></b>
            <a class="btn btn-danger btn-sm"
              href="{% url 'comps:comp_delete' comp.pc_name %}"
            >
              Удалить
            </a>
          </li>
          <li class="custom-list-item">
            <span class="custom-list-item-name">Дата добавления:</span>
            <span class="custom-list-item-value">{{ comp.add_date|date:"d E Y" }}</span>
          </li>
          <li class="custom-list-item {% if comp.is_offline_long_time %} blinking-text {% endif %}">
            <span class="custom-list-item-name">Дата онлайн:</span>
            <span class="custom-list-item-value">{{ comp.online_date|date:"d E Y" }}</span>
          </li>
          <li class="custom-list-item">
            <span class="custom-list-item-name">Департамент:</span>
            <span class="custom-list-item-value">{{ comp.department }}</span>
          </li>
          <li class="custom-list-item">
            <span class="custom-list-item-name">Версия ОС:</span>
            <span class="custom-list-item-value">{{ comp.win_ver }}</span>
          </li>
          <li class="custom-list-item">
            <span class="custom-list-item-name">Архитектура ОС:</span>
            <span class="custom-list-item-value">{{ comp.os_arch }}</span>
          </li>
          <li class="custom-list-item">
            <span class="custom-list-item-name">Процессор:</span>
            <span class="custom-list-item-value">{{ comp.cpu }}</span>
          </li>
          <li class="custom-list-item">
            <span class="custom-list-item-name">Материнская плата:</span>
            <span class="custom-list-item-value">{{ comp.motherboard }}</span>
          </li>
          <!-- <li class="custom-list-item">
            <span class="custom-list-item-name">Монитор:</span>
            <span class="custom-list-item-value">{{ comp.monitor }}</span>
          </li> -->
          <li class="custom-list-item">
            <span class="custom-list-item-name">Веб-камера:</span>
            <span class="custom-list-item-value">{{ comp.web_camera }}</span>
          </li>
        </ul>
      </div>
      <div class="col-md-6">
        <h6>Диски</h6>
        <table class="table">
          <thead>
            <tr>
              <th>Модель</th>
              <th>Объем</th>
              <th>S/N</th>
              <th>Статус</th>
              <th>Установлен</th>
              <th>Снят/Потерян</th>
            </tr>
          </thead>
          <tbody>
            {% for disk in comp.disks.all %}
              <tr class="{% if disk.status == 'installed' %}table-success{% elif disk.status == 'lost' %}table-danger{% else %}table-secondary{% endif %}">
                <td>{{ disk.model }}</td>
                <td>{{ disk.capacity }}</td>
                <td>{{ disk.serial_number }}</td>
                <td>{{ disk.get_status_display }}</td>
                <td>{{ disk.install_date|date:"d.m.Y H:i" }}</td>
                <td>{{ disk.uninstall_date|date:"d.m.Y H:i" }}</td>
                <td>
                  {% if disk.status == 'uninstalled' %}
                    <a class="btn btn-primary btn-sm"
                      href="{% url 'comps:item_edit' pc_name=comp.pc_name item='disk' item_status='installed' item_id=disk.id %}"
                    >Установить</a>
                  {% else %}
                    <a class="btn btn-primary btn-sm"
                      href="{% url 'comps:item_edit' pc_name=comp.pc_name item='disk' item_status='uninstalled' item_id=disk.id %}"
                    >Снять</a>
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
      </div>
      <div class="col-md-6">
        <h6>Оперативная память</h6>
        <table class="table">
          <thead>
            <tr>
              <th>Модель</th>
              <th>Объем</th>
              <th>S/N</th>
              <th>Статус</th>
              <th>Установлен</th>
              <th>Снят/Потерян</th>
            </tr>
          </thead>
          <tbody>
            {% for ram in comp.rams.all %}
              <tr class="{% if ram.status == 'installed' %}table-success{% elif ram.status == 'lost' %}table-danger{% else %}table-secondary{% endif %}">
                <td>{{ ram.model }}</td>
                <td>{{ ram.capacity }}</td>
                <td>{{ ram.serial_number }}</td>
                <td>{{ ram.get_status_display }}</td>
                <td>{{ ram.install_date|date:"d.m.Y H:i" }}</td>
                <td>{{ ram.uninstall_date|date:"d.m.Y H:i" }}</td>
                <td>
                  {% if ram.status == 'uninstalled' %}
                    <a class="btn btn-primary btn-sm"
                      href="{% url 'comps:item_edit' pc_name=comp.pc_name item='ram' item_status='installed' item_id=ram.id %}"
                    >Установить</a>
                  {% else %}
                    <a class="btn btn-primary btn-sm"
                      href="{% url 'comps:item_edit' pc_name=comp.pc_name item='ram' item_status='uninstalled' item_id=ram.id %}"
                    >Снять</a>
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
      </div>
      <div class="col-md-6">
        <h6>Мониторы</h6>
        <table class="table">
          <thead>
            <tr>
              <th>Модель</th>
              <th>Производитель</th>
              <th>S/N</th>
              <th>Статус</th>
              <th>Установлен</th>
              <th>Снят/Потерян</th>
            </tr>
          </thead>
          <tbody>
            {% for monitor in comp.monitors.all %}
              <tr class="{% if monitor.status == 'installed' %}table-success{% elif monitor.status == 'lost' %}table-danger{% else %}table-secondary{% endif %}">
                <td>{{ monitor.model }}</td>
                <td>{{ monitor.manufacturer }}</td>
                <td>{{ monitor.serial_number }}</td>
                <td>{{ monitor.get_status_display }}</td>
                <td>{{ monitor.install_date|date:"d.m.Y H:i" }}</td>
                <td>{{ monitor.uninstall_date|date:"d.m.Y H:i" }}</td>
                <td>
                  {% if monitor.status == 'uninstalled' %}
                    <a class="btn btn-primary btn-sm"
                      href="{% url 'comps:item_edit' pc_name=comp.pc_name item='monitor' item_status='installed' item_id=monitor.id %}"
                    >Установить</a>
                  {% else %}
                    <a class="btn btn-primary btn-sm"
                      href="{% url 'comps:item_edit' pc_name=comp.pc_name item='monitor' item_status='uninstalled' item_id=monitor.id %}"
                    >Снять</a>
                  {% endif %}
                </td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
{% endblock %}

invent_pc/templates/comps/comps_by_items.html
<!-- templates/comps_by_items.html -->

{% extends 'base.html' %}
{% block title %}
  {{ item }}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <h3>Компьютеры c "{{ item }}"</h3>
    {% include 'includes/filter_department.html' %}
  </div>
  <div class="container-fluid py-3 custom-container">
    {% include 'comps/includes/table_comps.html' %}
    {% include 'includes/paginator.html' %}
  </div>
{% endblock %}

invent_pc/templates/comps/departments.html
<!-- templates/departments.html -->

{% extends 'base.html' %}
{% block title %}
  Департаменты
{% endblock %}
{% block content %}
  <div class="container">
    <div class="text-center"><h4>Департаменты</h4></div>
    <table class="table table-striped table-bordered table-sm">
      <tr>
        <th>Название</th>
        <th>Количество</th>
      </tr>
      {% for department in departments %}
        <tr>
          <td>
            {{ department }}
            {% if not department.comp.count %}
              <a class="btn btn-outline-danger btn-sm float-end" 
                href="{% url 'comps:department_delete' department.id %}"
              >
                &#10060;
              </a>
            {% endif %}
          </td>
          <td>
            {{ department.comp.count }}
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>
{% endblock %}

invent_pc/templates/comps/reports.html
<!-- templates/reports.html -->

{% extends 'base.html' %}
{% block title %}
  Общая статистика
{% endblock %}
{% block content %}
  <div class="container">
    <div class="text-center"><h4>Общая статистика</h4></div>
    <div class="row">
      <div class="col">
        <table class="table table-bordered table-sm border-secondary">
          <tr>
            <th>#</th>
            <th>Количество</th>
          </tr>
          <tr>
            <td>Всего</td>
            <td>{{ comps_count }}</td>
          </tr>
          {% for item, count in count_by_os_arch %}
            {% if not item == 'total' %}
              <tr>
                <td>
                  {% with request.GET.department as department %}
                    <a
                      href="{% url 'comps:comps_by_item' item_type='os_arch' %}?item={{ item }}&department={{ department }}"
                    >{{ item }}</a>
                  {% endwith %}
                </td>
                <td>{{ count }}</td>
              </tr>
            {% endif %}
          {% endfor %}
          {% for item, count in count_by_win_ver %}
            {% if not item == 'total' %}
              <tr>
                <td>
                  {% with request.GET.department as department %}
                    <a
                      href="{% url 'comps:comps_by_item' item_type='win_ver' %}?item={{ item }}&department={{ department }}"
                    >{{ item }}</a>
                  {% endwith %}
                </td>
                <td>
                  {{ count }}
                </td>
              </tr>
            {% endif %}
          {% endfor %}
        </table>
      </div>
      <div class="col">
        {% include 'includes/filter_department.html' %}
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="row">
        <div class="col">
          <table class="table table-striped table-bordered table-sm">
            <tr>
              <th>Материнские платы</th>
              <th>Количество</th>
            </tr>
            {% for item, count in count_by_motherboard %}
            <tr>
              <td>
                {% if item == 'total' %}
                  <b>Всего</b>
                {% else %}
                  {% with request.GET.department as department %}
                    <a
                      href="{% url 'comps:comps_by_item' item_type='motherboard' %}?item={{ item }}&department={{ department }}"
                    >{{ item }}</a>
                  {% endwith %}
                {% endif %}
              </td>
              <td>{{ count }}</td>
            </tr>
            {% endfor %}
          </table>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <table class="table table-striped table-bordered table-sm">
            <tr>
              <th>Оперативная память</th>
              <th>Количество</th>
            </tr>
            {% for item, count in count_by_rams %}
            <tr>
              <td>
                {% if item == 'total' %}
                  <b>Всего</b>
                {% else %}
                  {% with request.GET.department as department %}
                    <a
                      href="{% url 'comps:comps_by_item' item_type='rams' %}?item={{ item }}&department={{ department }}"
                    >{{ item }}</a>
                  {% endwith %}
                {% endif %}
              </td>
              <td>{{ count }}</td>
            </tr>
            {% endfor %}
          </table>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="row">
        <div class="col">
          <table class="table table-striped table-bordered table-sm">
            <tr>
              <th>Процессоры</th>
              <th>Количество</th>
            </tr>
            {% for item, count in count_by_cpu %}
            <tr>
              <td>
                {% if item == 'total' %}
                  <b>Всего</b>
                {% else %}
                  {% with request.GET.department as department %}
                    <a
                      href="{% url 'comps:comps_by_item' item_type='cpu' %}?item={{ item }}&department={{ department }}"
                    >{{ item }}</a>
                  {% endwith %}
                {% endif %}
              </td>
              <td>{{ count }}</td>
            </tr>
            {% endfor %}
          </table>
        </div>
      </div>
      <div class="row">
        <div class="col`">
          <table class="table table-striped table-bordered table-sm">
            <tr>
              <th>Мониторы</th>
              <th>Количество</th>
            </tr>
            {% for item, count in count_by_monitors %}
            <tr>
              <td>
                {% if item == 'total' %}
                  <b>Всего</b>
                {% else %}
                  {% with request.GET.department as department %}
                    <a
                      href="{% url 'comps:comps_by_item' item_type='monitors' %}?item={{ item }}&department={{ department }}"
                    >{{ item }}</a>
                  {% endwith %}
                {% endif %}
              </td>
              <td>{{ count }}</td>
            </tr>
            {% endfor %}
          </table>
        </div>
      </div>
    </div>
    <div class="col">
      <table class="table table-striped table-bordered table-sm">
        <tr>
          <th>Диски</th>
          <th>Количество</th>
        </tr>
        {% for item, count in count_by_disks %}
        <tr>
          <td>
            {% if item == 'total' %}
              <b>Всего</b>
            {% else %}
              {% with request.GET.department as department %}
                <a
                  href="{% url 'comps:comps_by_item' item_type='disk' %}?item={{ item }}&department={{ department }}"
                >{{ item }}</a>
              {% endwith %}
            {% endif %}
          </td>
          <td>{{ count }}</td>
        </tr>
        {% endfor %}
      </table>
    </div>
  </div>
{% endblock %}