invent_pc/api/urls.py
from django.conf import settings
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from api.views import CompCreateViewSet, HostCreateViewSet


# Версия API
API_VERSION = settings.API_VERSION

router = DefaultRouter()
router.register('comps', CompCreateViewSet)
router.register('vms', HostCreateViewSet)

urlpatterns = [
    path(f'{API_VERSION}/', include(router.urls)),
]

invent_pc/invent_pc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('comps.urls', namespace='comps')),
]

invent_pc/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'


urlpatterns = [
    path('edit-user/', views.edit_user, name='edit_user'),
    path('get-rdlogins/', views.get_rdlogins, name='get_rdlogins'),
    path('get-vpns/', views.get_vpns, name='get_vpns'),
    path('update-users-data/',
         views.update_users_data,
         name='update_users_data'),
    path('generate-users-report/',
         views.generate_users_report,
         name='generate_users_report'),
    path('generate-radius-report/',
         views.generate_radius_report,
         name='generate_radius_report'),
    path('generate-vpn-report/',
         views.generate_vpn_report,
         name='generate_vpn_report'),
    path('login/', auth_views.LoginView.as_view(
        template_name='users/registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='users/registration/logged_out.html'), name='logout'),
    path('ad/', views.users_main, name='users_main'),
    path('radius/', views.users_radius, name='users_radius'),
    path('vpn/', views.users_vpn, name='users_vpn'),
    path('gigro/', views.users_gigro, name='users_gigro'),
]

invent_pc/users/models.py
from typing import Any
from django.db import models

from services.models import MySQLDatabase


class StatusChoices(models.TextChoices):
    ACTIVE = 'active', 'Активен'
    INACTIVE = 'inactive', 'Неактивен'


class BaseUserMixin(models.Model):
    """Базовая модель учетных записей из внешних систем."""
    login = models.CharField('Логин', unique=True, max_length=100)
    status = models.CharField(
        max_length=15,
        choices=StatusChoices.choices,
        default=StatusChoices.INACTIVE,
        verbose_name='Статус',
    )
    successfully_updated = models.BooleanField(
        default=True,
        verbose_name='Успешно обновлена',
        help_text=('Если информация об учетной записи не поступила '
                   'при последнем обновлении, галочка снимается, '
                   'запись можно удалить.')
    )
    expiry_date = models.DateField(
        'Срок действия',
        null=True,
        blank=True
    )

    @classmethod
    def add_user_to_block(cls, login: str) -> None:
        if not hasattr(cls, '_users_to_block'):
            cls._users_to_block = []
        cls._users_to_block.append(login)

    @classmethod
    def get_users_to_block(cls) -> list[str]:
        if not hasattr(cls, '_users_to_block'):
            cls._users_to_block = []
        return cls._users_to_block

    @classmethod
    def clear_users_for_blocking(cls) -> None:
        if hasattr(cls, '_users_to_block'):
            cls._users_to_block.clear()

    def needs_update(self, user_data):
        """Добавляет всем учетным записям метод для проверки изменений.
        user_data - данные учетной записи полученные из внешней системы.
        """
        needs_update = False
        for key, value in user_data.items():
            if getattr(self, key) != value:
                setattr(self, key, value)
                needs_update = True
        return needs_update

    class Meta:
        abstract = True


class ADUsers(BaseUserMixin):
    fio = models.CharField('ФИО', max_length=200)
    email = models.EmailField('Email', blank=True, null=True)
    rdlogin = models.ForeignKey(
        'Radius',
        on_delete=models.SET_NULL,
        related_name='ad_user',
        null=True,
        blank=True,
        verbose_name='Учетная запись Radius'
    )
    vpn = models.ForeignKey(
        'VPN',
        on_delete=models.SET_NULL,
        related_name='ad_user',
        null=True,
        blank=True,
        verbose_name='Учетная запись VPN'
    )

    def __init__(self, *args: Any, **kwargs: Any) -> None:
        super().__init__(*args, **kwargs)
        self.cached_status = self.status

    def __str__(self):
        return f'{self.fio} ({self.login})'

    @property
    def is_blocked(self) -> str:
        """Проверяет был ли пользователь заблокирован."""
        return (self.cached_status == StatusChoices.ACTIVE
                and self.status == StatusChoices.INACTIVE)

    def save(self, *args: Any, **kwargs: Any) -> None:
        """Добавляет пользователей в список на блокировку
        если учетная запись была заблокирована."""
        if self.is_blocked:
            ADUsers.add_user_to_block(self)
        return super().save(*args, **kwargs)

    class Meta:
        ordering = ('fio',)
        verbose_name = 'Пользователь AD'
        verbose_name_plural = 'Пользователи AD'


class Radius(BaseUserMixin):
    fio = models.CharField('ФИО', max_length=200)

    def __str__(self):
        return self.login

    @classmethod
    def get_users_to_block(cls) -> list[str]:
        if not hasattr(cls, '_users_to_block'):
            cls._users_to_block = []
        ad_users = ADUsers.get_users_to_block()
        for ad_user in ad_users:
            if ad_user.rdlogin:
                radius_user = ad_user.rdlogin
                radius_user.status = StatusChoices.INACTIVE
                cls._users_to_block.append(radius_user)
        return cls._users_to_block

    class Meta:
        ordering = ('login',)
        verbose_name = 'Пользователь WiFi'
        verbose_name_plural = 'Пользователи WiFi'


class VPN(BaseUserMixin):
    comment = models.TextField('Комментарий', blank=True, null=True)

    def __str__(self):
        return self.login

    @classmethod
    def get_users_to_block(cls) -> list[str]:
        if not hasattr(cls, '_users_to_block'):
            cls._users_to_block = []
        ad_users = ADUsers.get_users_to_block()
        for ad_user in ad_users:
            if ad_user.vpn:
                vpn_user = ad_user.vpn
                vpn_user.status = StatusChoices.INACTIVE
                cls._users_to_block.append(vpn_user)
        return cls._users_to_block

    class Meta:
        ordering = ('login',)
        verbose_name = 'Пользователь VPN'
        verbose_name_plural = 'Пользователи VPN'


class Gigrotermon(BaseUserMixin):
    login = models.CharField('Логин', max_length=50)
    db = models.ForeignKey(
        MySQLDatabase,
        on_delete=models.CASCADE,
        verbose_name='БД Гигротермон',
    )
    gigro_id = models.IntegerField(
        'Гигро id',
        help_text='ID в БД Гигротермон'
    )
    ad_user = models.ForeignKey(
        ADUsers,
        verbose_name='Пользователь AD',
        on_delete=models.CASCADE,
        related_name='gigro',
        null=True,
        blank=True
    )

    def __str__(self):
        return self.login

    @classmethod
    def get_users_to_block(cls) -> list[str]:
        if not hasattr(cls, '_users_to_block'):
            cls._users_to_block = []
        return cls._users_to_block

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['login', 'db'],
                name='unique_login_db'
            )
        ]
        ordering = ('login',)
        verbose_name = 'Пользователь Гигротермон'
        verbose_name_plural = 'Пользователи Гигротермон'

invent_pc/users/views.py
import json
import logging

from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from rest_framework import status

from exceptions.services import MissingVariableError, RadiusUsersNotFoundError

from .filters import (UsersFilter, RadiusUsersFilter,
                      VPNUsersFilter, GigroUsersFilter)
from .models import VPN, ADUsers, Radius, Gigrotermon
from .utils import (get_file, get_radius_file,
                    get_vpn_file, get_users_base_context)
from .update_gigrotermon import update_gigrotermon
from .update_ad import update_ad
from .update_vpn import update_vpn
from .update_radius import update_radius
from .update_rocket import update_rocket

logger = logging.getLogger(__name__)


@login_required
def users_main(request):
    """Список всех учетных записей из AD."""
    ad_users = (ADUsers.objects.all()
                .select_related('rdlogin', 'vpn')
                .prefetch_related('gigro'))
    user_filter = UsersFilter(request.GET, queryset=ad_users)
    context = get_users_base_context(request, user_filter)
    context['header'] = 'Active Directory'
    context['table_template'] = 'users/includes/table_users.html'

    return render(request, 'users/users.html', context)


@login_required
def users_radius(request):
    """Список всех учетных записей Radius."""
    radius_users = Radius.objects.all().prefetch_related('ad_user')
    user_filter = RadiusUsersFilter(request.GET, queryset=radius_users)
    context = get_users_base_context(request, user_filter)
    context['header'] = 'Wi-Fi'
    context['table_template'] = 'users/includes/table_users_radius.html'

    return render(request, 'users/users.html', context)


@login_required
def users_vpn(request):
    """Список всех учетных записей VPN."""
    vpn_users = VPN.objects.all().prefetch_related('ad_user')
    user_filter = VPNUsersFilter(request.GET, queryset=vpn_users)
    context = get_users_base_context(request, user_filter)
    context['header'] = 'VPN'
    context['table_template'] = 'users/includes/table_users_vpn.html'

    return render(request, 'users/users.html', context)


@login_required
def users_gigro(request):
    """Список всех учетных записей Гигротермон."""
    gigro_users = Gigrotermon.objects.all().select_related('ad_user')
    user_filter = GigroUsersFilter(request.GET, queryset=gigro_users)
    context = get_users_base_context(request, user_filter)
    context['header'] = 'Гигротермон'
    context['table_template'] = 'users/includes/table_users_gigro.html'

    return render(request, 'users/users.html', context)


@login_required
def edit_user(request):
    """Редактирование связаных учетных записей пользователя."""
    if request.method == 'POST':
        ad_user_id = request.POST.get('ad_user_id')
        login_id = request.POST.get('rdlogin_id') or request.POST.get('vpn_id')
        field = request.POST.get('field')
        ad_user = ADUsers.objects.get(id=ad_user_id)
        setattr(ad_user, field, login_id)
        ad_user.save()
        return JsonResponse({'success': True}, status=status.HTTP_200_OK)

    if request.method == 'DELETE':
        body = json.loads(request.body.decode('utf-8'))
        ad_user_id = body.get('ad_user_id')
        ad_user = ADUsers.objects.get(id=ad_user_id)
        field = body.get('field')
        setattr(ad_user, field, None)
        ad_user.save()
        return JsonResponse({'success': True}, status=status.HTTP_200_OK)

    return JsonResponse({'success': False},
                        status=status.HTTP_405_METHOD_NOT_ALLOWED)


@login_required
def get_rdlogins(request):
    """Получить список доступных учетных записей Radius."""
    rdlogins = list(Radius.objects.filter(ad_user=None).values('id', 'login'))
    return JsonResponse(rdlogins, safe=False)


@login_required
def get_vpns(request):
    """Получить список доступных учетных записей VPN."""
    vpns = list(VPN.objects.filter(ad_user=None).values('id', 'login'))
    return JsonResponse(vpns, safe=False)


@login_required
def update_users_data(request):
    """Обновляет учетные данные из внешних систем.
    - Active Directory
    - WiFi Radius
    - VPN Mikrotik
    """
    try:
        # Обновление учетных записей
        update_ad()
        update_rocket()
        update_vpn()
        update_radius()
        update_gigrotermon()

    except (MissingVariableError, RadiusUsersNotFoundError) as error:
        logger.error(str(error))
        return JsonResponse(
            {'success': False, 'error': str(error)},
            status=status.HTTP_400_BAD_REQUEST
        )
    except Exception as error:
        logger.exception(f'Необработанная ошибка: {str(error)}')
        return JsonResponse(
            {'success': False, 'error': str(error)},
            status=status.HTTP_400_BAD_REQUEST
        )
    finally:
        ADUsers.clear_users_for_blocking()
        Radius.clear_users_for_blocking()
        VPN.clear_users_for_blocking()
    return JsonResponse({'success': True}, status=status.HTTP_200_OK)


@login_required
def generate_users_report(request):
    """Формирует список связных учетных записей, отдает файлом Excel."""
    users = ADUsers.objects.all().filter(
        Q(rdlogin__isnull=False) | Q(vpn__isnull=False)
        ).select_related('rdlogin', 'vpn')

    excel_file = get_file(users)

    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')  # noqa
    response['Content-Disposition'] = 'attachment; filename="ad_users_report.xlsx"'  # noqa

    excel_file.save(response)

    return response


@login_required
def generate_radius_report(request):
    """Формирует список свободных учетных запитсей Radius,
    отдает файлом Excel."""
    users = Radius.objects.filter(ad_user__isnull=True)

    excel_file = get_radius_file(users)

    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')  # noqa
    response['Content-Disposition'] = 'attachment; filename="radius_users_report.xlsx"'  # noqa

    excel_file.save(response)

    return response


@login_required
def generate_vpn_report(request):
    """Формирует список свободных учетных запитсей VPN,
    отдает файлом Excel."""
    users = VPN.objects.filter(ad_user__isnull=True)

    excel_file = get_vpn_file(users)

    response = HttpResponse(content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')  # noqa
    response['Content-Disposition'] = 'attachment; filename="vpn_users_report.xlsx"'  # noqa

    excel_file.save(response)

    return response

invent_pc/templates/users/includes/buttons_types_users.html
<!-- templates/users/includes/buttons_types_users.html -->

<div class="btn-group" role="group">
  {% with request.resolver_match.view_name as view_name %}
    <a
      href="{% url 'users:users_main' %}"
      class="btn btn-outline-primary btn-sm {% if view_name == 'users:users_main' %}active{% endif %}"
    >Active Directory</a>
  {% endwith %}
  {% with request.resolver_match.view_name as view_name %}
    <a
      href="{% url 'users:users_radius' %}"
      class="btn btn-outline-primary btn-sm {% if view_name == 'users:users_radius' %}active{% endif %}"
    >Wi-Fi</a>
  {% endwith %}
  {% with request.resolver_match.view_name as view_name %}
    <a
      href="{% url 'users:users_vpn' %}"
      class="btn btn-outline-primary btn-sm {% if view_name == 'users:users_vpn' %}active{% endif %}"
    >VPN</a>
  {% endwith %}
  {% with request.resolver_match.view_name as view_name %}
    <a
      href="{% url 'users:users_gigro' %}"
      class="btn btn-outline-primary btn-sm {% if view_name == 'users:users_gigro' %}active{% endif %}"
    >Гигротермон</a>
  {% endwith %}
</div>

invent_pc/templates/users/includes/edit_expiry_date.html
<!-- templates/users/includes/edit_expiry_date.html -->

<td>
  <button class="btn btn-sm edit-expiry-date-btn" data-user-id="{{ user.id }}">&#128221;</button>
  <button class="btn btn-sm delete-expiry-date-btn" data-user-id="{{ user.id }}">&#128465;</button>
  <button class="btn btn-sm save-expiry-date-btn" data-user-id="{{ user.id }}" style="display: none;">&#128190;</button>
  <span id="display_expiration_{{ user.id }}" data-account-type="{{ account_type }}">{{ user.expiry_date|date:"d.m.Y" }}</span>
  <input type="date" id="input_expiration_{{ user.id }}" value="{{ user.expiry_date }}" style="display:none;">
  <p class="error-message" id="error_message_{{ user.id }}" style="display:none;color:red;"></p>
</td>

invent_pc/templates/users/includes/table_users.html
<!-- templates/users/includes/table_users.html -->

<table class="table table-striped table-hover">
  <tr>
    <th>ФИО</th>
    <th>Логин</th>
    <form action="{% url 'users:users_main' %}" method="get">
      {% for key, value in request.GET.items %}
        <input type="hidden" name="{{ key }}" value="{{ value }}">
      {% endfor %}
      <th>Email
        <button class="btn btn-sm btn-outline-secondary" type="submit" name="email" value="True">&#9993;</button>
      </th>
      <th>Статус
        <button class="btn btn-sm btn-outline-secondary" type="submit" name="status" value="active">&#9989;</button>
        <button class="btn btn-sm btn-outline-secondary" type="submit" name="status" value="inactive">&#10060;</button>
      </th>
      <th>Логин Wi-Fi
        <button class="btn btn-sm btn-outline-secondary" type="submit" name="rdlogin" value="active">&#9989;</button>
        <button class="btn btn-sm btn-outline-secondary" type="submit" name="rdlogin" value="inactive">&#10060;</button>
      </th>
      <th>Логин VPN
        <button class="btn btn-sm btn-outline-secondary" type="submit" name="vpn" value="active">&#9989;</button>
        <button class="btn btn-sm btn-outline-secondary" type="submit" name="vpn" value="inactive">&#10060;</button>
      </th>
      <th>
        Гигротермон
        <button class="btn btn-sm btn-outline-secondary" type="submit" name="gigro" value="active">&#9989;</button>
        <button class="btn btn-sm btn-outline-secondary" type="submit" name="gigro" value="inactive">&#10060;</button>
      </th>
    </form>
  </tr>
  {% for user in page_obj %}
    <tr data-user-id="{{ user.id }}">
      <td>
        {{ user.fio }}
        {% if not user.successfully_updated %}⚠️(устарела){% endif %}
      </td>
      <td>{{ user.login }}</td>
      <td>{% if user.email %}{{ user.email }}{% endif %}</td>
      <td>
        {% if user.status == 'active' %}
          <span>&#9989;</span>
        {% else %}
          <span>&#10060;</span>
        {% endif %}
      </td>
      <td class="editable-field">
        <button class="btn btn-sm edit-rdlogin-btn">&#128221;</button>
        <button class="btn btn-sm delete-rdlogin-btn">&#128465;</button>
        <button class="btn btn-sm save-rdlogin-btn" style="display: none;">&#128190;</button>
        <button class="btn btn-sm cancel-rdlogin-btn" style="display: none;">&#10006;</button>
        <span class="current-value rdlogin-value">
          {{ user.rdlogin|default_if_none:"-" }}
          {% if user.rdlogin.status == 'active' %}
            <span>&#9989;</span>
          {% elif user.rdlogin.status == 'inactive'  %}
            <span>&#10060;</span>
          {% endif %}
        </span>
        <select name="rdlogin" class="form-control edit-select" style="display: none;"></select>
      </td>
      <td class="editable-field">
        <button class="btn btn-sm edit-vpn-btn">&#128221;</button>
        <button class="btn btn-sm delete-vpn-btn">&#128465;</button>
        <button class="btn btn-sm save-vpn-btn" style="display: none;">&#128190;</button>
        <button class="btn btn-sm cancel-vpn-btn" style="display: none;">&#10006;</button>
        <span class="current-value vpn-value">
          {{ user.vpn|default_if_none:"-" }}
          {% if user.vpn.status == 'active' %}
            <span>&#9989;</span>
          {% elif user.vpn.status == 'inactive'  %}
            <span>&#10060;</span>
          {% endif %}
        </span>
        <select name="vpn" class="form-control edit-select" style="display: none;"></select>
      </td>
      <td>
        {% for gigro_user in user.gigro.all %}
          {{ gigro_user.login }}-{{ gigro_user.db }}
          {% if gigro_user.status == 'active' %}
            <span>&#9989;</span>
          {% elif gigro_user.status == 'inactive'  %}
            <span>&#10060;</span>
          {% endif %}{% if not gigro_user.successfully_updated %}⚠️(устарела){% endif %}<br>
          {% empty %}
              -
        {% endfor %}
      </td>
    </tr>
  {% endfor %}
</table>

invent_pc/templates/users/includes/table_users_gigro.html
<!-- templates/users/includes/table_users_gigro.html -->

<table class="table table-striped table-hover">
  <tr>
    <th>Логин</th>
    <th>БД Гигротермон</th>
    <form action="{% url 'users:users_gigro' %}" method="get">
      <th>Статус
        <button class="btn btn-sm btn-outline-secondary" type="submit" name="status" value="active">&#9989;</button>
        <button class="btn btn-sm btn-outline-secondary" type="submit" name="status" value="inactive">&#10060;</button>
      </th>
    </form>
    <th>Гигротермон-id</th>
    <th>Пользователь AD</th>
    <th>Срок действия</th>
  </tr>
  {% for user in page_obj %}
    <tr data-user-id="{{ user.id }}">
      <td>
        {{ user.login }}
        {% if not user.successfully_updated %}⚠️(устарела){% endif %}
      </td>
      <td>{{ user.db }}</td>
      <td>
        {% if user.status == 'active' %}
          <span>&#9989;</span>
        {% else %}
          <span>&#10060;</span>
        {% endif %}
      </td>
      <td>{{ user.gigro_id }}</td>
      <td>
        {{ user.ad_user|default_if_none:"-" }}
        {% if user.ad_user.status == 'active' %}
          <span>&#9989;</span>
        {% elif user.ad_user.status == 'inactive' %}
          <span>&#10060;</span>
        {% endif %}
      </td>
      {% include 'users/includes/edit_expiry_date.html' %}
    </tr>
  {% endfor %}
</table>

invent_pc/templates/users/includes/table_users_radius.html
<!-- templates/users/includes/table_users_radius.html -->

<table class="table table-striped table-hover">
  <tr>
    <th>ФИО</th>
    <th>Логин</th>
    <form action="{% url 'users:users_radius' %}" method="get">
      <th>Статус
        <button class="btn btn-sm btn-outline-secondary" type="submit" name="status" value="active">&#9989;</button>
        <button class="btn btn-sm btn-outline-secondary" type="submit" name="status" value="inactive">&#10060;</button>
      </th>
    </form>
    <th>Пользователь AD</th>
    <th>Срок действия</th>
  </tr>
  {% for user in page_obj %}
    <tr data-user-id="{{ user.id }}">
      <td>
        {{ user.fio }}
        {% if not user.successfully_updated %}⚠️(устарела){% endif %}
      </td>
      <td>{{ user.login }}</td>
      <td>
        {% if user.status == 'active' %}
          <span>&#9989;</span>
        {% else %}
          <span>&#10060;</span>
        {% endif %}
      </td>
      <td>
        {% for ad_user in user.ad_user.all %}
          {{ ad_user }}
          {% if ad_user.status == 'active' %}
            <span>&#9989;</span>
          {% elif ad_user.status == 'inactive'  %}
            <span>&#10060;</span>
          {% endif %}
          {% empty %}
              -
        {% endfor %}
      </td>
      {% include 'users/includes/edit_expiry_date.html' %}
    </tr>
  {% endfor %}
</table>

invent_pc/templates/users/includes/table_users_report.html
<!-- templates/users/includes/table_users_report.html -->

<table class="table table-striped table-bordered table-sm border-secondary">
  <thead>
    <tr style="text-align: center">
    <th>Сервис</th>
    <th colspan="2">Активна &#9989;</th>
    <th colspan="2">Неактивна &#10060;</th>
    <th colspan="2">Всего</th>
    </tr>
  </thead>
  <tbody>
    <tr style="text-align: center">
    <td style="text-align: left">Active Directory</td>
    <td colspan="2" class="{% if request.GET.status == 'active' %}bold-text{% endif %}">
        {{ ad_users_statuses.active }}
    </td>
    <td colspan="2" class="{% if request.GET.status == 'inactive' %}bold-text{% endif %}">
        {{ ad_users_statuses.inactive }}
    </td>
    <td colspan="2">{{ ad_users_statuses.total }}</td>
    </tr>
    <tr>
    <td></td>
    <td colspan="6" style="font-size: 12px;">
        * Привязанные / непривязанные
    </td>
    </tr>
    <tr style="text-align: center">
    <td style="text-align: left">Wi-Fi</td>
    <td class="{% if request.GET.rdlogin == 'active' %}bold-text{% endif %}">
        {{ radius_users_statuses.active }}
    </td>
    <td>{{ unrelated_radius_users_statuses.active }}</td>
    <td class="{% if request.GET.rdlogin == 'inactive' %}bold-text{% endif %}">
        {{ radius_users_statuses.inactive }}
    </td>
    <td>{{ unrelated_radius_users_statuses.inactive }}</td>
    <td>{{ radius_users_statuses.total }}</td>
    <td>{{ unrelated_radius_users_statuses.total }}</td>
    </tr>
    <tr style="text-align: center">
    <td style="text-align: left">VPN</td>
    <td class="{% if request.GET.vpn == 'active' %}bold-text{% endif %}">
        {{ vpn_users_statuses.active }}
    </td>
    <td>{{ unrelated_vpn_users_statuses.active }}</td>
    <td class="{% if request.GET.vpn == 'inactive' %}bold-text{% endif %}">
        {{ vpn_users_statuses.inactive }}
    </td>
    <td>{{ unrelated_vpn_users_statuses.inactive }}</td>
    <td>{{ vpn_users_statuses.total }}</td>
    <td>{{ unrelated_vpn_users_statuses.total }}</td>
    </tr>
  </tbody>
</table>

invent_pc/templates/users/includes/table_users_vpn.html
<!-- templates/users/includes/table_users_vpn.html -->

<table class="table table-striped table-hover">
  <tr>
    <th>Логин</th>
    <th>Комментарий</th>
    <form action="{% url 'users:users_vpn' %}" method="get">
      <th>Статус
        <button class="btn btn-sm btn-outline-secondary" type="submit" name="status" value="active">&#9989;</button>
        <button class="btn btn-sm btn-outline-secondary" type="submit" name="status" value="inactive">&#10060;</button>
      </th>
    </form>
    <th>Пользователь AD</th>
    <th>Срок действия</th>
  </tr>
  {% for user in page_obj %}
    <tr data-user-id="{{ user.id }}">
      <td>
        {{ user.login }}
        {% if not user.successfully_updated %}⚠️(устарела){% endif %}
      </td>
      <td>
        {{ user.comment|default_if_none:"-" }}
      </td>
      <td>
        {% if user.status == 'active' %}
          <span>&#9989;</span>
        {% else %}
          <span>&#10060;</span>
        {% endif %}
      </td>
      <td>
        {% for ad_user in user.ad_user.all %}
          {{ ad_user }}
          {% if ad_user.status == 'active' %}
            <span>&#9989;</span>
          {% elif ad_user.status == 'inactive'  %}
            <span>&#10060;</span>
          {% endif %}
          {% empty %}
              -
        {% endfor %}
      </td>
      {% include 'users/includes/edit_expiry_date.html' %}
    </tr>
  {% endfor %}
</table>