invent_pc/api/urls.py
from django.conf import settings
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from api.views import CompCreateViewSet, HostCreateViewSet


# Версия API
API_VERSION = settings.API_VERSION

router = DefaultRouter()
router.register('comps', CompCreateViewSet)
router.register('vms', HostCreateViewSet)

urlpatterns = [
    path(f'{API_VERSION}/', include(router.urls)),
]

invent_pc/comps/urls.py
from django.urls import path

from . import views

app_name = 'comps'


urlpatterns = [
    path('', views.index, name='index'),
    path('reports/',
         views.reports, name='reports'),
    path('comps_by_item/<slug:item_type>/',
         views.comps_by_item, name='comps_by_item'),
    path('departments/',
         views.departments, name='departments'),
    path('vms/', views.vms, name='vms'),
    path('departments/<int:department_id>/delete',
         views.department_delete, name='department_delete'),
    path('<str:pc_name>/', views.comp_detail, name='comp_detail'),
    path('<str:pc_name>/<str:item>/<slug:item_status>/<int:item_id>',
         views.item_edit, name='item_edit'),
    path('<str:pc_name>/delete/',
         views.comp_delete, name='comp_delete'),
]

invent_pc/invent_pc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('', include('comps.urls', namespace='comps')),
]

invent_pc/users/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'users'


urlpatterns = [
    path('edit-user/', views.edit_user, name='edit_user'),
    path('get-rdlogins/', views.get_rdlogins, name='get_rdlogins'),
    path('get-vpns/', views.get_vpns, name='get_vpns'),
    path('update-users-data/',
         views.update_users_data,
         name='update_users_data'),
    path('generate-users-report/',
         views.generate_users_report,
         name='generate_users_report'),
    path('generate-radius-report/',
         views.generate_radius_report,
         name='generate_radius_report'),
    path('generate-vpn-report/',
         views.generate_vpn_report,
         name='generate_vpn_report'),
    path('login/', auth_views.LoginView.as_view(
        template_name='users/registration/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
        template_name='users/registration/logged_out.html'), name='logout'),
    path('ad/', views.users_main, name='users_main'),
    path('radius/', views.users_radius, name='users_radius'),
    path('vpn/', views.users_vpn, name='users_vpn'),
    path('gigro/', views.users_gigro, name='users_gigro'),
]

invent_pc/templates/includes/filter_department.html
<!-- templates/includes/filter_department.html -->

<form method="get">
  {% for key, value in request.GET.items %}
    {% if key != 'department' %}
      <input type="hidden" name="{{ key }}" value="{{ value }}">
      {% endif %}
  {% endfor %}
  {{ filter_form.as_p }}
  <button class="btn btn-primary btn-sm" type="submit">Фильтровать</button>
</form>

invent_pc/templates/includes/footer.html
<!-- templates/includes/footer.html -->

<p>
  <span style="color:rgb(15, 112, 215)">Comp</span><span style="color:rgb(22, 211, 8)">any</span>
  Inventory - Copyright © {{ year }}
</p>

invent_pc/templates/includes/header.html
<!-- templates/includes/header.html -->

<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href="{% url 'comps:index' %}">
      {% load static %}
      <img
        src="{% static 'img/logo.png' %}"
        width="60"
        height="30"
        class="d-inline-block align-top"
        alt="">
      Company Inventory
    </a>
    <ul class="nav nav-pills">
      {% with request.resolver_match.view_name as view_name %}
        <li>
          <a class="nav-link {% if view_name  == 'comps:index' %}active{% endif %}"
            href="{% url 'comps:index' %}"
          >
            Главная
          </a>
        </li>
      {% endwith %}
      {% with request.resolver_match.view_name as view_name %}
        <li> 
          <a class="nav-link {% if view_name  == 'comps:departments' %}active{% endif %}"
            href="{% url 'comps:departments' %}"
          >
            Департаменты
          </a>
        </li>
      {% endwith %}
      {% with request.resolver_match.view_name as view_name %}
        <li> 
          <a class="nav-link {% if view_name  == 'comps:vms' %}active{% endif %}"
            href="{% url 'comps:vms' %}"
          >
            Гипервизоры
          </a>
        </li>
      {% endwith %}
      {% with request.resolver_match.view_name as view_name %}
        <li>
          <a class="nav-link 
            {% if view_name == 'users:users_main' or view_name == 'users:users_radius' or view_name == 'users:users_vpn' or view_name == 'users:users_gigro' %}
              active
            {% endif %}"
            href="{% url 'users:users_main' %}"
          >
            Учетные записи
          </a>
        </li>
      {% endwith %}
      {% with request.resolver_match.view_name as view_name %}
        <li> 
          <a class="nav-link {% if view_name  == 'comps:reports' %}active{% endif %}"
            href="{% url 'comps:reports' %}"
          >
            Отчеты
          </a>
        </li>
      {% endwith %}
    </ul>
  </div>
  <div class="mx-auto">
    {% if user.is_authenticated %}
      <small>{{ user.get_full_name }}: {{ user.username }}</small>
      <a class="btn btn-outline-secondary" href="{% url 'users:logout' %}">Выйти</a>
    {% endif %}
  </div>
</nav>

invent_pc/templates/includes/paginator.html
<!-- templates/includes/paginator.html -->

{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page=1&{{ current_query_params.urlencode }}">Первая</a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}&{{ current_query_params.urlencode }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}&{{ current_query_params.urlencode }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}&{{ current_query_params.urlencode }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}&{{ current_query_params.urlencode }}">
          Последняя
        </a>
      </li>
    {% endif %}
  </ul>
</nav>
{% endif %}